version: '3.8'

services:
  # Ollama service (solo acceso interno)
  ollama-cpu:
    image: ollama/ollama:latest
    container_name: ollama-cloudflare-ai
    # Sin puertos expuestos públicamente
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - ai-internal

  # Open WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-cloudflare
    # Sin puertos expuestos públicamente
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama-cloudflare-ai:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-change-this-secret-key}
      - WEBUI_JWT_SECRET_KEY=${WEBUI_JWT_SECRET_KEY:-change-this-jwt-secret}
    depends_on:
      - ollama-cpu
    restart: unless-stopped
    networks:
      - ai-internal

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ai-cloudflare-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - open-webui
    restart: unless-stopped
    networks:
      - ai-internal

networks:
  ai-internal:
    driver: bridge

volumes:
  ollama_data:
  open_webui_data:
