version: '3.8'

services:
  # Servicio Ollama (mantiene la configuración original)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-web-ai
    ports:
      - "127.0.0.1:11434:11434"  # Solo acceso local
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu
    
  # Versión sin GPU
  ollama-cpu:
    image: ollama/ollama:latest
    container_name: ollama-web-ai-cpu
    ports:
      - "127.0.0.1:11434:11434"  # Solo acceso local
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - ai-network
    profiles:
      - cpu

  # Open WebUI - Interfaz principal
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-public
    ports:
      - "127.0.0.1:3001:8080"  # Solo acceso local
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama-cpu:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-change-this-secret-key}
      - WEBUI_JWT_SECRET_KEY=${WEBUI_JWT_SECRET_KEY:-change-this-jwt-secret}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-true}
    depends_on:
      - ollama-cpu
    restart: unless-stopped
    networks:
      - ai-network
    profiles:
      - cpu
      
  # Nginx como proxy reverso con SSL
  nginx:
    image: nginx:alpine
    container_name: ai-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - open-webui
    restart: unless-stopped
    networks:
      - ai-network
    profiles:
      - cpu

  # Certbot para SSL automático (Let's Encrypt)
  certbot:
    image: certbot/certbot
    container_name: ai-certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d your-domain.com
    profiles:
      - ssl

networks:
  ai-network:
    driver: bridge

volumes:
  ollama_data:
  open_webui_data:
  nginx_logs:
